### ISSUE TITLE
Make SelenideFieldDecorator and ElementsContainerCollection accessible

### ISSUE THREAD

**Issue by Vuskk5** [selenide/selenide#1360]
## The problem
I want to use some custom annotations for processing fields / elements.
IE: Extending the `@FindBy` annotation for more strategies and adding other annotations.

## Details
I need to implement the PageFactory myself, as I do not have access to `SelenideFieldDecorator`.
I need to create custom classes which extends `SelenideFieldDecorator` & `SelenidePageFactory` and implement `decorate()` differently. (IE: Use another class to build the `By` locator)
At the moment both `SelenideFieldDecorator` & `ElementsContainerCollection` have package-private access,
which blocks from calling them.
Setting them both public would solve this issue.

Another solution could be:

The ability to configure the annotation proccessing class,
which is coded as `org.openqa.selenium.support.pagefactory.Annotations` in the decorate() function.

## Tell us about your environment
* **Selenide Version**: 5.17.2

**Comment by asolntsev** [comment]
WIP

**Comment by Vuskk5** [comment]
@asolntsev My only need really is to use another class instead of `Annotations`.

I now have looked into changing the classes and it would really require a lot of changes to both of them.

Right now I am copying both classes and making all the changes I need.
My idea was to make both classes be friendly when extending them, and by that I would only need to override several functions which create the `SelenideFieldDecorator` for example and add static method to the PageFactory in order to use it.

I would really appreciate if this could be done using the plugins system.

**Comment by asolntsev** [comment]
@Vuskk5 yes, i am going töö make these classes customizable.

Can i ask what `Annotations` you use? Is it Appium?

**Comment by Vuskk5** [comment]
@asolntsev I am using my own `Annotations`, it is used to find an ElementContainer's head by an inner element (each `ElementContainer` has a known class, I locate an inner element and find the ancestor with the given class).
I also extend the locators that the normal `@FindBy` provide with some selenide locators such as `text()`.

**Comment by asolntsev** [comment]
@Vuskk5 Do you initialise page objects using method `Selenide.page(Class)`? 
Is it ok if we add method `Selenide.page(Class, Class<Annotations>)`?

**Comment by Vuskk5** [comment]
@asolntsev I do not use `Selenide.page(Class)` I rather call a static method defined in my PageFactory,
which calls `page(Driver, Class<PageObjectClass>)` with `WebDriverRunner.driver()` to get the driver.

Yes, adding such a method would be really great and will solve my issue.

The only drawback is that I would probably need to wrap it since passing the `Annotations` on every call would make classes a little ugly, yet again, this is a much better solution than the one I currently have.

**Comment by asolntsev** [comment]
@Vuskk5 Well, I tried to do the following:

1. Call `new Annotations(field).buildBy()` in `SelenidePageFactory` instead of `SelenideFieldDecorator`. 
  So you only need to override one class (`SelenideFieldDecorator`). 

2. Extracted this call to a separate **protected** method:
```java
  protected By findSelector(Field field) {
    return new Annotations(field).buildBy();
  }
```

3. Now you only need to override one small method `findSelector` in `YourFieldDecorator`. 
4. Is it ok for you? Do you need some other parameters in addition to `Field`?

**Comment by Vuskk5** [comment]
@asolntsev I do not need other parameters, this function would satisfy my needs.
It would allow me to only override one method in `MyFieldDecorator`, which is incredible.
But how can I pass `MyFieldDecorator` to the `SelenidePageFactory`?
Do I need to create my own class and override `initElements()` calls? (Which is still a big improvement for me)

**Comment by asolntsev** [comment]
@Vuskk5 I am working on it. My plan is to make it as simple as possible to pass custom `Annotations` to `SelenidePageFactory`.

**Comment by asolntsev** [comment]
@Vuskk5 Can you take a look at my PR https://github.com/selenide/selenide/pull/1362/files ?
You will need to override just one method `SelenideOageFactory.findSelector()`.

**Comment by Vuskk5** [comment]
@asolntsev Looks great to me, should solve my problem,
If I understand the plugins system correctly, I need to extend `SelenidePageFactory` and `inject` will pick up my implementation automatically? Or do I need to provide it as a config?
Anyway, this PR seems to solve the issue.

**Comment by asolntsev** [comment]
@Vuskk5 I have released Selenide 5.17.3

Just create a subclass of `SelenidePageFactory` and override only one method in it: 
```
  @Nonnull
  protected By findSelector(Field field) {
    return new Annotations(field).buildBy();
  }
```

Now you have two options to use your factory:
1. Just create it as you did before, like `MyPage page = new YourPageFactory().page(driver(), MyPage.class);`
2. Create a file `src/test/resources/com.codeborne.selenide.impl.PageObjectFactory` with content `com.your.company.YourPageFactory` - this way Selenide method `inject` will detect your factory and use it instead of `SelenidePageFactory` (this mechanism is called [ServiceLoader](https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/util/ServiceLoader.html)).

**Comment by Vuskk5** [comment]
@asolntsev I have updated to 5.17.3 now, but still one problem remains:
Because I am using an annotation different than `@FindBy` (I am using something customized for out project),
`isDecoratableList` returns false because it checks for `FindBy.class` or `FindBys.class`.
Any ideas how would I solve this issue?
At the worst case I can refactor the pages and use `@FindBy`, but It is nice to extend those annotations so I can get more from them.

**Comment by asolntsev** [comment]
@Vuskk5 we can make isDecoratableList() protected, so that you could override it.

**Comment by Vuskk5** [comment]
@asolntsev That would be great, would it be injected just like `MyPageFactory`?

**Comment by asolntsev** [comment]
@Vuskk5 In Selenide 5.17.4, I will remove class `SelenideFieldDecorator`. All its logic will be moved to `SelenidePageFactory`. All methods are `protected`. So that you can just override method `isDecoratableList`. See PR https://github.com/selenide/selenide/pull/1368
