### ISSUE TITLE
Collection filtering by visibility

### ISSUE THREAD

**Issue by pavelpp** [selenide/selenide#681]
## The problem
Filtering collection by visibility and then clicking on the first visible element throws exception 'Element should be visible'

## Details
Given page elements:

```
public ElementsCollection tooltipIcons = $$(".icon-info").filter(visible);
public SelenideElement tooltipIcon = tooltipIcons.first();
```

When I call `tooltipIcon.click()` I will get an exception saying that element is not visible; In reality it checks the first element from unfiltered collection, which is indeed invisible in my case. Works fine with 4.9. Looks like `filter(visible)` does not actually do anything.

## Tell us about your environment
* **Selenide Version:** 4.10.01

UPDATE: Looks like it works the first time, but once element visibility changes and I try to access element via the same page object reference the filtering is not re-triggered and it's trying to access the same element as before, which is not visible anymore.

**Comment by vinogradoff** [comment]
Could not reproduce. Could you either give HTML as example or try to get this test failing:

https://github.com/codeborne/selenide/blob/c409fa9a9d9f7f5899d63ad9dfb85bbc9dba76d1/src/test/java/integration/CollectionMethodsTest.java method canChainFilterAndFirst()

**Comment by pavelpp** [comment]
@vinogradoff , well it also passes if add `click()` after `shouldHave(text("non-clickable element"))` so is the test actually valid?

**Comment by pavelpp** [comment]
OK, got it failing by modifying test a bit:
```  
@Test
  public void canChainFilterAndFirst() {
    $$("div").filterBy(visible).first().shouldHave(id("clickable-element"));
    $$("div").filterBy(visible).get(2).click();
  }
```

**Comment by vinogradoff** [comment]
Actually the first three divs are:

- hidden

- #non-clickable-element

- #clickable-element


so the first line *should* fail :)


it fails for me in chrome clicking on “clickable-element”
filter(visible)get(1).click()
- but it looks almost like bug in selenium or even chromedriver….



Viele Grüße

Alexei Vinogradov

On 23. Januar 2018 at 12:11:56, pavelpp (notifications@github.com) wrote:

OK, got it failing by modifying test a bit:

@Test
  public void canChainFilterAndFirst() {
    $$("div").filterBy(visible).first().shouldHave(id("clickable-element"));
    $$("div").filterBy(visible).get(2).click();
  }

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/codeborne/selenide/issues/681#issuecomment-359758247>,
or mute the thread

**Comment by pavelpp** [comment]
Oh, my bad, id is about clickability, not visibility. I'll experiment some more

**Comment by pavelpp** [comment]
This is really weird. I can't make it fail in this test. In my actual test the collection is stored in a page field, could that be the decisive factor? I tried to reproduce with a simple page object but I can't make it fail with the provided test page. In my case it fails consistently, unless I do double filtering in the test itself:
```
visibleDivs.filter(visible).first().click();
```
this will pass, however this will fail
```
visibleDivs.first().click();
```

**Comment by vinogradoff** [comment]
Can you export your HTML and try to delete everything irrelevant?

**Comment by pavelpp** [comment]
Finally I understand what's going on. It's not a problem of Selenide. I use DI for a page object and access it's public fields in steps implementation. Doing new Page().someField fixes the issue.

**Comment by pavelpp** [comment]
perhaps the problem is the before Selenide was going through collection filters and first() on every call and now it's caching such collections instead.

**Comment by vinogradoff** [comment]
intended is that filter/first etc. doesn’t search until .should/click etc
is called.


so it is probably a bug in 4.9 :)


should we close?

Viele Grüße

Alexei Vinogradov

On 23. Januar 2018 at 13:02:30, pavelpp (notifications@github.com) wrote:

perhaps the problem is the before Selenide was going through collection
filters and first() on every call and now it's caching such collections
instead.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/codeborne/selenide/issues/681#issuecomment-359769575>,
or mute the thread

**Comment by pavelpp** [comment]
@vinogradoff if @asolntsev confirms that's the way it's supposed to work from now on. It can be a problem if I created an instance of a page object and did something with element, then it's visibility changed and when I try to do something again, it will not look for visible elements, but instead try to use the same element again. Not sure that's the way it should be.

**Comment by pavelpp** [comment]
Let's imagine collection is declared in a page object as a field:
```
public class MyPage{
ElementsCollection visibleDivs = $$("div").filter(visible);
SelenideElement firstVisibleDiv = visibleDivs.first();
}
```
Suppose I do this:

```
MyPage page = new MyPage();
page.firstVisibleDiv.click();
// now this div becomes invisible;
page.firstVisibleDiv.click(); --> should find next visible element from visibleDivs and click on that instead of clicking on previous element that became invisible;
```

**Comment by vinogradoff** [comment]
```
MyPage.filtered_element.click();
// now element should be searched again, because of filtering
MyPage.filtered_element.click();
```
Funny case :) For me personally it looks fishy. 
If I read this code I would probably never excpect, that filtered_element can change from line 1 to line 3....

But it is interesting, that it could be one reason to use Object PO over Static PO, because you can solve it (please check it) very easy, with Object POs.

This code should always work:
```
new MyPage().filtered_element.click();
// now element should be searched again, because of filtering
new MyPage().filtered_element.click();
```
And makes a bit more sense, because new MyPage() reads as "evaluate the PO again"

**Comment by pavelpp** [comment]
yes, that's what I'm saying before it was not needed to instantiate page object again and elements would be requested lazily on each click() ( in version 4.9). From now on it's gonna change. Users need to be made aware of that change

**Comment by vinogradoff** [comment]
This looks like "never evaluation", classically lazy evaluation = "evaluate by first usage" != "evaluate by every usage". But I don't think we had special thought on that difference before... 

@asolntsev @yashaka FYI

**Comment by vinogradoff** [comment]
```MyPage page = new MyPage();
page.firstVisibleDiv.click();
// now this div becomes invisible;
page.firstVisibleDiv.click();
```

Acutally even this should work, because of re-search after StaleElementException from Selenium....

Probably we still need a short working example with a problem reproduced.

**Comment by pavelpp** [comment]
any volunteers to implement such test page? I can't provide example from our product, cause it's React and so on - it becomes too complicated.

**Comment by pavelpp** [comment]
OK, I created a working example and I can confirm that it's reproducible. See example:

```
        Selenide.open("https://f000.backblazeb2.com/file/pavelp-shared/pageWithTabs.html");

        ElementsCollection visibleHeaders = $$("h3").filter(Condition.visible);
        SelenideElement firstHeader = visibleHeaders.first();
        ElementsCollection tabs = $$("button");

        firstHeader.shouldHave(Condition.text("London"));
        tabs.last().click();
        firstHeader.shouldBe(Condition.visible).shouldHave(Condition.text("Tokyo"));
```

**Comment by sidelnikovmike** [comment]
@pavelpp As I see in html - after select `Tokyo` -  h3 element on page has `displayed:none`. Is your page correct?

**Comment by pavelpp** [comment]
@sidelnikovmike please double-check. Shows` displayed: block;` for me

**Comment by sidelnikovmike** [comment]
<img width="648" alt="image" src="https://user-images.githubusercontent.com/10669327/42085967-8599d27c-7b9a-11e8-9a89-fca8d431b097.png">

as you can see - for london - display:none. In code you check first element(London).
Your code is incorrect, I think. 
Your `visibleHeader` always be 'London', but you want it to be `Tokyo`. 
I think now it works as designed.

**Comment by pavelpp** [comment]
@sidelnikovmike sorry, I thought you meant Tokyo. No it's not how I expect this to work. I check first VISIBLE h3 , which is what I filter for. That h3 should be dynamic, changing at the time of polling for element text. Like I said earlier it used to work like that before caching was introduced in version 4.10.01.

**Comment by sidelnikovmike** [comment]
@pavelpp I think it is strange behaviour. You first have link to first element, but after some manipulations you wait, that there is another element. Not so understandable code.
@asolntsev What do you think?

**Comment by asolntsev** [comment]
@pavelpp @sidelnikovmike It was intentional change in Selenide 4.10: http://selenide.org/2018/01/12/selenide-4.10/

- Before 4.10, Selenide re-loaded the whole collection on every `$$` method. It could be slow.
- Starting from 4.10, Selenide "caches" the collection, and only re-evaluates it in `$$.should*` methods (if check fails). 

We had lot of discussions which behaviour is more correct.

- I personally like the new behaviour. And I agree with @sidelnikovmike that the code above is strange: you put one element to a variable and later expect that it contains another element.
- But other folks argued that the old behaviour is better because it's consistent with `$` behaviour. It reloads the element on every `$` method. 

This argument was strong enough for me, so I plan to revert the old behaviour (still trying to save performance of iteration through `$$`). Thought, still could not find not time to do it. :)

**Comment by rosolko** [comment]
Already discuss. Currently multiple implementation using in code. So for first need to choose default and then introduce parameter and switch behavior based on.

**Comment by pavelpp** [comment]
Yes, I agree the example is a bit artificial, it's purely to demonstrate what was working before and not working anymore. There are certain use cases for this and consistency is also a concern.

**Comment by asolntsev** [comment]
I think this issue was fixed in Selenide 4.12.3: http://selenide.org/2018/07/17/selenide-4.12.3/

@pavelpp Can you confirm? Then we could close the issue.

**Comment by qtpsudhakar** [comment]
The issue still exist in 4.12.3

We have tried with all types of element wait techniques. Still we get stalement exception. The page gets reloaded and we are finding the element again with $$(By.xpath("[xpath]")).filter(visible);
But it is finding the previous document reference instead of current document element.
But if we give thread.sleep(50000) then it works with latest document.
We thought that it is page loading issue and tried all types of ajax framework related wait using javascript. But when we dig deeper we understood that $$ works with previous driver reference but not with latest loaded document. When we give thread.sleep it is working with the latest loaded document.
How to avoid this?
Is there any facility to instruct selenide to work with latest loaded html document when it reloads?

**Comment by asolntsev** [comment]
@qtpsudhakar I confirm that Selenide 4.12.3+ always works with latest loaded html document (well, except `$$.iterator()`. 

I cannot reproduce your problem. I tried, but I cannot.
Can you send me a code sample that would reproduce the problem?

**Comment by asolntsev** [comment]
Closing due to inactivity
